// Chữ tượng hình & hội ý: [chữ, nghĩa, nhóm, biểu tượng gợi nhớ, gợi ý hình, cách nhớ]
// Nhóm: tn = thiên nhiên, ng = con người & cơ thể, dv = động vật, gh = ghép chữ, vd = vật dụng & khác
// Các cách nhớ mang tính gợi ý để dễ học, không phải lúc nào cũng là nguồn gốc học thuật.
const HANZI=[
['日','mặt trời, ngày','tn','☀','vòng tròn có một vệt sáng','Vẽ mặt trời thành hình tròn (sau này vuông lại); nét ngang ở giữa là vệt sáng.'],
['月','mặt trăng, tháng','tn','☾','vầng trăng khuyết','Hình trăng khuyết; hai nét ngang bên trong là các vệt mờ trên mặt trăng.'],
['木','cây, gỗ','tn','🌳','thân, cành và rễ','Nét ngang là cành, nét sổ là thân, hai nét xòe xuống là rễ.'],
['林','rừng nhỏ','gh','🌲','hai cây đứng cạnh nhau','Hai chữ 木 ghép lại: nhiều cây thành rừng nhỏ.'],
['森','rừng rậm','gh','🌲','ba cây chụm lại','Ba chữ 木: càng nhiều cây thì rừng càng rậm.'],
['水','nước','tn','💧','dòng nước và các giọt bắn ra','Nét sổ giữa là dòng chảy, các nét hai bên là giọt nước bắn tung.'],
['火','lửa','tn','🔥','ngọn lửa có tia lửa bắn ra','Ngọn lửa ở giữa, hai bên là tàn lửa bay ra.'],
['山','núi','tn','⛰','ba đỉnh núi','Ba đỉnh núi, đỉnh giữa cao nhất.'],
['雨','mưa','tn','🌧','trời, mây và các giọt mưa','Nét ngang trên cùng là bầu trời, khung bên dưới là mây, bốn chấm là giọt mưa rơi.'],
['田','ruộng','tn','🌾','các ô ruộng chia bởi bờ','Hình thửa ruộng vuông, nét chữ thập là bờ chia ruộng thành các ô.'],
['土','đất','tn','🌱','mầm nhú lên từ mặt đất','Nét ngang dưới là mặt đất, nét sổ là mầm cây nhô lên.'],
['石','đá','tn','🪨','vách đá và hòn đá','Phần 厂 là vách núi, 口 bên dưới là hòn đá lăn xuống.'],
['人','người','ng','🧍','người đứng nghiêng, hai chân','Một người nhìn nghiêng với thân và hai chân bước.'],
['大','to, lớn','ng','🙆','người dang rộng tay chân','Chữ 人 thêm hai tay dang rộng, như đang nói "to cỡ này".'],
['口','miệng','ng','👄','cái miệng há ra','Hình cái miệng đang mở.'],
['目','mắt','ng','👁','con mắt vẽ dựng đứng','Con mắt vẽ dọc; hai nét ngang bên trong là con ngươi.'],
['耳','tai','ng','👂','vành tai','Hình vành tai với phần xoáy bên trong.'],
['手','tay','ng','✋','bàn tay với các ngón','Các nét ngang là ngón tay, nét sổ móc là cổ tay và cánh tay.'],
['心','tim, tâm','ng','❤','quả tim và mạch máu','Nét móc ở giữa là thân tim, ba chấm là máu và mạch.'],
['女','phụ nữ','ng','♀','người ngồi quỳ, hai tay đan trước','Hình người phụ nữ ngồi quỳ, hai tay khoanh trước ngực.'],
['子','con, đứa trẻ','ng','👶','đứa bé dang tay','Hình đứa trẻ đầu to, hai tay dang ra, chân quấn tã.'],
['母','mẹ','ng','👩','chữ 女 thêm hai chấm','Là chữ 女 có thêm hai chấm, tượng trưng cho bầu ngực nuôi con.'],
['好','tốt, hay','gh','👍','女 + 子','Người mẹ (女) bên đứa con (子): điều tốt đẹp, hạnh phúc.'],
['休','nghỉ ngơi','gh','🛏','人 + 木','Người (亻) dựa lưng vào cây (木) để nghỉ.'],
['明','sáng','gh','💡','日 + 月','Mặt trời (日) và mặt trăng (月) cùng chiếu: rất sáng.'],
['看','nhìn','gh','👀','手 + 目','Bàn tay (手) đưa lên che trên mắt (目) để nhìn xa.'],
['从','theo, từ','gh','🚶','hai người nối đuôi nhau','Hai chữ 人 đi liền nhau: người sau đi theo người trước.'],
['家','nhà','gh','🏠','mái nhà + con lợn','宀 là mái nhà, 豕 là con lợn: xưa kia nhà có nuôi lợn mới gọi là "nhà".'],
['安','bình yên','gh','🏡','mái nhà + người phụ nữ','女 ở dưới mái nhà (宀): có người ở trong nhà thì yên ổn.'],
['字','chữ','gh','✍','đứa con dưới mái nhà','子 dưới mái 宀: chữ cũng "sinh sôi" ra như con cái trong nhà.'],
['问','hỏi','gh','❓','miệng đứng ở cửa','口 đứng ở cửa 门: đến cửa, mở miệng để hỏi.'],
['男','nam, đàn ông','gh','👨','ruộng + sức lực','田 (ruộng) + 力 (sức): người dùng sức để làm ruộng.'],
['牛','con bò','dv','🐄','đầu bò có hai sừng','Nét ngang là hai sừng, nét sổ là sống mặt bò.'],
['羊','dê, cừu','dv','🐑','hai sừng cong','Nét phía trên là hai sừng cong, bên dưới là thân và chân.'],
['马','ngựa','dv','🐴','bờm và thân ngựa','Từ hình con ngựa có bờm, chân và đuôi, giản thể hóa còn ít nét.'],
['鱼','cá','dv','🐟','đầu, thân và đuôi cá','Phía trên là đầu cá, ô vuông là thân, nét ngang dưới là đuôi.'],
['鸟','chim','dv','🐦','chim có mắt và mỏ','Chấm là mắt chim, các nét còn lại là mỏ, thân và chân.'],
['虫','sâu bọ','dv','🐛','con sâu cuộn tròn','Hình con sâu nhỏ đang cuộn mình.'],
['米','gạo','vd','🍚','hạt gạo tỏa ra bốn phía','Nét ngang là bông lúa, các chấm xung quanh là hạt gạo.'],
['王','vua','vd','♛','ba tầng nối bằng một nét','Ba nét ngang là trời, người, đất; nét sổ nối cả ba: vua kết nối trời đất.'],
['工','công việc, thợ','vd','🛠','dụng cụ của người thợ','Hình thước góc của người thợ; sau này chỉ "công việc".'],
['刀','dao','vd','🔪','lưỡi dao có cán','Nét móc là cán và sống dao, nét phẩy là lưỡi.'],
['车','xe','vd','🚗','bánh xe nhìn từ trên','Hình chiếc xe nhìn từ trên: nét ngang là trục, ô vuông là thùng xe.'],
['门','cửa','vd','🚪','hai cánh cửa','Hình hai cánh cửa mở sang hai bên.'],
['小','nhỏ','vd','▫','một vật bị chia nhỏ','Nét giữa bị hai chấm tách ra hai bên: vật bị chia nhỏ dần.'],
['上','trên','vd','⬆','nét ngang và dấu hiệu ở trên','Nét ngang dài là mặt đất, nét ngắn phía trên chỉ vị trí "bên trên".'],
['下','dưới','vd','⬇','nét ngang và dấu hiệu ở dưới','Dấu nằm dưới nét ngang chỉ vị trí "bên dưới".'],
['中','giữa, trong','vd','🎯','mũi tên xuyên vào giữa','Nét sổ xuyên qua giữa ô vuông: trúng ngay hồng tâm.']
];
