// Vocabulary parsed from "Từ vựng HSK 4" (your PDF). [word, pinyin, POS, meaning (Vietnamese), unit]
VOCAB.length=0;
VOCAB.push(
["爱情", "àiqíng", "Danh từ", "Tình yêu", 0],
["暗", "àn", "Tính từ", "Tối", 0],
["安排", "ānpái", "Danh từ", "Sắp xếp; An bài", 0],
["安全", "ānquán", "Danh từ", "An toàn", 0],
["按时", "ànshí", "Danh từ", "Đúng giờ Chuẩn giờ", 0],
["按照", "ànzhào", "Động từ", "Tuân theo Theo; ….", 0],
["抱", "bào", "Động từ", "Ôm; Bế; Ẵm", 0],
["报道", "bàodào", "Động từ", "Đưa tin, báo tin; Bài báo; Phóng sự", 0],
["保护", "bǎohù", "Động từ", "Bảo vệ Bảo hộ", 0],
["包括", "bāokuò", "Danh từ", "Bao gồm", 0],
["报名", "bàomíng", "Động từ", "Báo danh; Báo tên", 0],
["抱歉", "bàoqiàn", "Động từ", "Xin lỗi Thứ lỗi", 0],
["倍", "bèi", "Danh từ", "Lần; Lượng từ; Bội", 0],
["笨", "bèn", "Tính từ", "Ngốc nghếch", 0],
["本来", "běnlái", "Từ nối", "Vốn dĩ, ban đầu Có lẽ, lẽ ra, đáng lẽ", 0],
["遍", "biàn", "Lượng từ", "Đoạn", 0],
["表达", "biǎodá", "Động từ", "Biểu đạt; Bày tỏ", 0],
["表格", "biǎogé", "Danh từ", "Bảng, biểu", 0],
["表扬", "biǎoyáng", "Động từ", "Biểu dương; Tán/ tuyên dương", 0],
["标准", "biāozhǔn", "Danh từ", "Tiêu chuẩn", 0],
["笔记本", "bǐjìběn", "Danh từ", "Sổ tay", 0],
["饼干", "bǐnggān", "Danh từ", "Bánh quy", 0],
["并且", "bìngqiě", "Từ nối", "Hơn nữa; Liên từ", 0],
["毕业", "bìyè", "Danh từ", "Tốt nghiệp; Động từ", 0],
["博士", "bóshì", "Danh từ", "Tiến sĩ", 0],
["不但", "bù dàn", "Từ nối", "Không những n; Liên từ", 0],
["不得不", "bùdé bù", "Từ nối", "Không thể không; Cần phải", 0],
["部分", "bùfèn", "Danh từ", "Bộ phận", 0],
["不管", "bùguǎn", "Từ nối", "Cho dù; Bất kể; Bất luận; Mặc kệ, bỏ liều, bất chấp", 0],
["不过", "bùguò", "Từ nối", "Cực kỳ, hết mức, hơn hết; Phó từ; Chẳng qua, vừa mới, vừa chỉ", 0],
["不仅", "bùjǐn", "Từ nối", "Không chỉ", 0],
["擦", "cā", "Động từ", "Ma sát, xoa, cọ, quẹt; Sờ", 0],
["猜", "cāi", "Động từ", "Đoán", 0],
["材料", "cáiliào", "Danh từ", "Tài liệu", 0],
["参观", "cānguān", "Động từ", "Tham quan", 0],
["差不多", "chàbùduō", "Danh từ", "Xấp xỉ, gần giống nhau,không nhiều lắm; Bình thường", 0],
["尝", "cháng", "Động từ", "Nếm", 0],
["场", "chǎng", "Lượng từ", "Trận", 0],
["长城", "chángchéng", "Danh từ", "Trường Thành", 0],
["长江", "chángjiāng", "Danh từ", "Trường Giang", 0],
["吵", "chǎo", "Động từ", "Cãi nhau", 0],
["超过", "chāoguò", "Động từ", "Vượt qua", 0],
["成功", "chénggōng", "Danh từ", "Thành công; Động từ", 0],
["诚实", "chéngshí", "Tính từ", "Thành thực; Thật thà", 0],
["成熟", "chéngshú", "Động từ", "Thành thục; Trưởng thành; Chín chắn", 0],
["成为", "chéngwéi", "Động từ", "Trở thành", 0],
["乘坐", "chéngzuò", "Động từ", "Đi, đáp (máy bay, tàu hỏa, …)", 0],
["吃惊", "chījīng", "Động từ", "Kinh ngạc; Danh từ; Giật mình; Hoảng hốt", 0],
["重新", "chóngxīn", "Động từ", "Làm lại từ đầu; Làm mới", 0],
["抽烟", "chōuyān", "Động từ", "Hút thuốc", 0],
["窗户", "chuānghù", "Danh từ", "Cửa sổ", 0],
["传真", "chuánzhēn", "Danh từ", "Fax", 0],
["出差", "chūchāi", "Động từ", "Công tác; Danh từ", 0],
["出发", "chūfā", "Động từ", "xuất phát", 0],
["出生", "chūshēng", "Động từ", "Sinh ra; Ra đời", 0],
["词典", "cídiǎn", "Danh từ", "Từ điển", 0],
["从来", "cónglái", "Từ nối", "Chưa từng; Liên từ; Từ trước tới nay", 0],
["粗心", "cūxīn", "Động từ", "Sơ ý; Không cẩn thận; Thờ ơ", 0],
["答案", "dá'àn", "Danh từ", "Đáp án", 0],
["打扮", "dǎ bàn", "Động từ", "Trang điểm; Ăn vận", 0],
["大夫", "dàfū", "Danh từ", "Thầy thuốc; Đại phu; Có thể dùng để chỉ: tri thức", 0],
["大概", "dàgài", "Danh từ", "Khoảng Tầm", 0],
["代表", "dàibiǎo", "Động từ", "Đại biểu", 0],
["代替", "dàitì", "Động từ", "Thay thế", 0],
["当", "dāng", "Động từ", "Đang; Đương", 0],
["当地", "dāng dì", "Danh từ", "Bản địa; Bản xứ", 0],
["当时", "dāngshí", "Từ chỉ thời gian", "Đương thời; Lúc đó", 0],
["刀", "dāo", "Danh từ", "Dao", 0],
["到处", "dàochù", "Danh từ", "Khắp nơi", 0],
["到底", "dàodǐ", "Từ nối", "Rốt cục; Đến cùng", 0],
["道歉", "dàoqiàn", "Động từ", "Xin lỗi; Thứ lỗi", 0],
["导游", "dǎoyóu", "Danh từ", "Hướng dẫn viên du lịch", 0],
["打扰", "dǎrǎo", "Động từ", "Làm phiền", 0],
["大使馆", "dàshǐ guǎn", "Danh từ", "Đại sứ quản", 0],
["打印", "dǎyìn", "Động từ", "In ấn", 0],
["打折", "dǎzhé", "Động từ", "Giảm giá", 0],
["打针", "dǎzhēn", "Động từ", "Châm cứu", 0],
["得", "dé", "Trợ từ trạng thái", "Đắc", 0],
["等", "děng", "Động từ", "Đợi", 0],
["得意", "déyì", "Động từ", "Đắc ý", 0],
["低", "dì", "Tính từ", "Thấp", 0],
["掉", "diào", "Động từ", "Mất; Rơi, hạ, giảm", 0],
["调查", "diàochá", "Động từ", "Điều tra", 0],
["地球", "dìqiú", "Danh từ", "Địa cầu", 0],
["丢", "diū", "Động từ", "Mất", 0],
["地址", "dìzhǐ", "Danh từ", "Địa chỉ", 0],
["动作", "dòngzuò", "Động từ", "Động tác; Danh từ", 0],
["断", "duàn", "Động từ", "Đứt", 0],
["堵车", "dǔchē", "Động từ", "Tắc đường", 0],
["对话", "duìhuà", "Danh từ", "Đối thoại", 0],
["对面", "duìmiàn", "Danh từ", "Đối mặt; Đối diện", 0],
["顿", "dùn", "Lượng từ", "Bữa; Động từ; Ngừng", 0],
["朵", "duǒ", "Lương từ", "Đóa", 0],
["肚子", "dùzi", "Danh từ", "Bụng", 0],
["而", "ér", "Từ nối", "Nhưng; Liên từ; Mà", 0],
["儿童", "értóng", "Danh từ", "Nhi đồng; Trẻ em", 0],
["发", "fā", "Động từ", "Phát", 0],
["法律", "fǎlǜ", "Danh từ", "Pháp luật", 0],
["反对", "fǎnduì", "Động từ", "Phản đối", 0],
["方法", "fāngfǎ", "Danh từ", "Phương pháp", 0],
["方面", "fāngmiàn", "Danh từ", "Phương diện", 0],
["放弃", "fàngqì", "Động từ", "Vứt bỏ; Từ bỏ", 0],
["放暑假", "fàng shǔjià", "Động từ", "Nghỉ hè", 0],
["访问", "fǎngwèn", "Động từ", "Viếng thăm; Thăm hỏi", 0],
["方向", "fāngxiàng", "Danh từ", "Phương hướng", 0],
["烦恼", "fánnǎo", "Danh từ", "Phiền não; Buồn phiền", 0],
["范围", "fànwéi", "Danh từ", "Phạm vi", 0],
["翻译", "fānyì", "Danh từ", "Phiên dịch; Động từ", 0],
["反应", "fǎnyìng", "Động từ", "Phản ứng", 0],
["发生", "fāshēng", "Động từ", "Phát sinh; Xảy ra", 0],
["发展", "fāzhǎn", "Động từ", "Phát triển", 0],
["份", "fèn", "Lượng từ", "Phần", 0],
["丰富", "fēngfù", "Tính từ", "Phong phú", 0],
["风景", "fēngjǐng", "Danh từ", "Phong cảnh", 0],
["...分之...", "fēn zhī", "", "...phần...", 0],
["否则", "fǒuzé", "Liên từ", "Nếu không thì; Bằng không; Nếu không", 0],
["富", "fù", "Danh từ", "Giàu có; Sung túc; Phú", 0],
["符合", "fúhé", "Danh từ", "Phù hợp; Thích hợp", 0],
["父亲", "fùqīn", "Danh từ", "Bố đẻ; Phụ thân", 0],
["复印", "fùyìn", "Động từ", "Photocopy; Sao chép", 0],
["复杂", "fùzá", "Tính từ", "Phức tạp", 0],
["负责", "fú zé", "Động từ", "Phụ trách", 0],
["改变", "gǎibiàn", "Động từ", "Thay đổi", 0],
["干", "gàn", "Động từ", "Làm", 0],
["干杯", "gānbēi", "Động từ", "Cạn ly; Cạn cốc", 0],
["感动", "gǎndòng", "Động từ", "Cảm động", 0],
["刚刚", "gānggāng", "Trạng từ", "Vừa; Vừa mới Vừa vặn", 0],
["感觉", "gǎnjué", "Động từ", "Cảm giác", 0],
["感情", "gǎnqíng", "Danh từ", "Cảm tình Tình; Động từ cảm", 0],
["感谢", "gǎnxiè", "Động từ", "Cảm ơn", 0],
["干燥", "gānzào", "Tính từ", "Khô nóng; Khô hanh", 0],
["高级", "gāojí", "Phó từ", "Cao cấp", 0],
["各", "gè", "Lượng từ", "Mỗi, các", 0],
["个子", "gè zi", "Danh từ", "Vóc dáng; Dáng người Thân hình", 0],
["工具", "gōngjù", "Danh từ", "Công cụ", 0],
["公里", "gōnglǐ", "Đơn vị đo", "Km", 0],
["共同", "gòngtóng", "Trạng từ", "Đồng thời; Cùng nhau; Có chung", 0],
["工资", "gōngzī", "Danh từ", "Tiền lương", 0],
["够", "gòu", "Trạng từ", "Đủ", 0],
["购物", "gòuwù", "Động từ", "Mua sắm", 0],
["挂", "guà", "Động từ", "Treo móc", 0],
["逛", "guàng", "Động từ", "Dạo (phố)", 0],
["光", "guāng", "Danh từ", "Ánh sáng; Vầng quang", 0],
["广播", "guǎngbò", "Động từ", "Phát thanh; Truyền thanh", 0],
["广告", "guǎnggào", "Động từ", "Quảng cáo", 0],
["关键", "guānjiàn", "Tính từ", "Then chốt", 0],
["管理", "guǎnlǐ", "Động từ", "Quản lý", 0],
["观众", "guānzhòng", "Danh từ", "Quần chúng", 0],
["孤单", "gūdān", "Tính từ", "Cô đơn", 0],
["规定", "guīdìng", "Danh từ", "qui định; Động từ", 0],
["估计", "gūjìì", "Động từ", "Tính toán; Đánh giá, dự tính, nhận định, ước đoán", 0],
["顾客", "gùkè", "Danh từ", "Khách hàng", 0],
["鼓励", "gǔlì", "Động từ", "Cổ vũ", 0],
["过", "guò", "Động từ", "Qua", 0],
["过程", "guòchéng", "Danh từ", "Quá trình", 0],
["国际", "guójì", "Danh từ", "Quốc tế", 0],
["果然", "guǒrán", "Trạng từ", "Quả nhiên", 0],
["故意", "gùyì", "Trạng từ", "Cố ý; Động từ", 0],
["鼓掌", "gǔzhǎng", "Động từ", "Vỗ tay", 0],
["害羞", "hàixiū", "Động từ", "Ngại ngùng; Tính từ", 0],
["海洋", "hǎiyáng", "Danh từ", "Hải dương, biển cả", 0],
["汗", "hàn", "Danh từ", "Mồ hôi", 0],
["航班", "hángbān", "Danh từ", "Chuyến bay", 0],
["寒假", "hánjià", "Danh từ", "Nghỉ đông", 0],
["好处", "hǎochù", "Danh từ", "Điểm tốt; Ưu điểm", 0],
["号码", "hàomǎ", "Danh từ", "Số; Size, cỡ", 0],
["好像", "hǎoxiàng", "Động từ", "Giống như; Dường như", 0],
["合格", "hégé", "Danh từ", "Hợp lệ; Hợp cách; Đạt tiêu chuẩn", 0],
["合适", "héshì", "Phó từ", "Thích hợp", 0],
["盒子", "hézi", "Danh từ", "Cái hộp", 0],
["厚", "hòu", "Tính từ", "Dày (chỉ kích thước, độ dày)", 0],
["后悔", "hòuhuǐ", "Động từ", "Hối hận", 0],
["后来", "hòulái", "Trạng từ", "Sau này", 0],
["猴子", "hóuzi", "Danh từ", "Khỉ", 0],
["怀疑", "huáiyí", "Động từ", "Hoài nghi", 0],
["会议", "huìyì", "Động từ", "Hội ý; Danh từ", 0],
["火", "huǒ", "Danh từ", "Lửa; Hỏa; Để chỉ cái gì đó rất: …. hot", 0],
["获得", "huòdé", "Động từ", "Đạt được; Giành được", 0],
["活动", "huódòng", "Danh từ", "Hoạt động", 0],
["活泼", "huópō", "Tính từ", "Hoạt bát Nhanh nhẹn", 0],
["忽然", "hūrán", "Trạng từ", "Đột nhiên", 0],
["护士", "hùshì", "Danh từ", "Hộ lý", 0],
["互相", "hùxiāng", "Động từ", "Lẫn nhau", 0],
["寄", "jì", "Động từ", "Ký gửi gửi", 0],
["假", "jiǎ", "Tính từ", "Giả", 0],
["加班", "jiābān", "Động từ", "Tăng ca", 0],
["价格", "jiàgé", "Danh từ", "Giá cả", 0],
["家具", "jiājù", "Danh từ", "Nội thất", 0],
["坚持", "jiānchí", "Động từ", "Kiên trì", 0],
["减肥", "jiǎnféi", "Động từ", "Giảm cân", 0],
["降低", "jiàngdī", "Động từ", "Giảm thấp", 0],
["奖金", "jiǎngjīn", "Danh từ", "Tiền thưởng", 0],
["将来", "jiānglái", "Danh từ", "Tương lai", 0],
["减少", "jiǎnshǎo", "Động từ", "Giảm bớt", 0],
["交", "jiāo", "Động từ", "Giao; Đưa", 0],
["骄傲", "jiāo'ào", "Động từ", "Tự hào; Tính từ; Kiêu ngạo", 0],
["交流", "jiāoliú", "Động từ", "Giao lưu", 0],
["教授", "jiàoshòu", "Danh từ", "Giáo sư", 0],
["交通", "jiāotōng", "Động từ", "Giao thông", 0],
["教育", "jiàoyù", "Động từ", "Giáo dục", 0],
["饺子", "jiǎozi", "Danh từ", "Bánh chẻo; Sủi cảo; Dimsum", 0],
["加油站", "jiāyóu zhàn", "Danh từ", "Trạm xăng", 0],
["基础", "jīchǔ", "Danh từ", "Cơ sở Nền tảng", 0],
["激动", "jīdòng", "Động từ", "Kích động", 0],
["结果", "jiéguǒ", "Danh từ", "Kết quả", 0],
["解释", "jiěshì", "Động từ", "Giải thích", 0],
["接受", "jiēshòu", "Động từ", "Tiếp nhận", 0],
["节约", "jiéyuē", "Động từ", "Tiết kiệm", 0],
["集合", "jíhé", "Động từ", "Tập hợp; Danh từ; Tụ tập", 0],
["计划", "jìhuà", "Danh từ", "Kế hoạch", 0],
["积极", "jījí", "Tính từ", "Tích cực; Hăng hái", 0],
["积累", "jīlěi", "Động từ", "Tích lũy", 0],
["精彩", "jīngcǎi", "Tính từ", "Đặc sắc; Ưu việt, xuất sắc", 0],
["经常", "jīngcháng", "Phó từ", "Thường xuyên", 0],
["经济", "jīngjì", "Danh từ", "Kinh tế", 0],
["京剧", "jīngjù", "Danh từ", "Kinh kịch", 0],
["竟然", "jìngrán", "Phó từ", "Mà, lại; Vậy mà", 0],
["精神", "jīngshén", "Tính từ", "Tinh thần; Danh từ", 0],
["尽管", "jǐnguǎn", "Phó từ", "Vẫn, vẫn cứ; Cứ việc", 0],
["经验", "jīngyàn", "Danh từ", "Kinh nghiệm; Động từ", 0],
["竞争", "jìngzhēng", "Động từ", "Cạnh tranh", 0],
["镜子", "jìngzi", "Danh từ", "Cái gương", 0],
["进行", "jìnxíng", "Động từ", "Tiến hành", 0],
["紧张", "jǐnzhāng", "Tính từ", "Lo lắng; Hồi hộp", 0],
["禁止", "jìnzhǐ", "Động từ", "Cấm", 0],
["极其", "jíqí", "Trạng từ", "Cực kì; Vô cùng", 0],
["既然", "jìrán", "Liên từ", "Đã, nếu đã", 0],
["及时", "jíshí", "Từ chỉ thời gian", "Kịp thời", 0],
["即使", "jíshǐ", "Liên từ", "Cho dù; Từ nối; Dù cho", 0],
["技术", "jìshù", "Danh từ", "Kỹ thuật", 0],
["究竟", "jiùjìng", "Phó từ", "Cuối cùng", 0],
["继续", "jìxù", "Động từ", "Tiếp tục (không dừng lại, không ngắt quãng)", 0],
["记者", "jìzhě", "Danh từ", "ký giả; phóng viên; nhà báo", 0],
["举办", "jǔbàn", "Động từ", "Tổ chức; Cử hành", 0],
["拒绝", "jùjué", "Động từ", "Cự tuyệt; Từ chối", 0],
["距离", "jùlí", "Danh từ", "Khoảng cách; Cự ly", 0],
["开玩笑", "kāiwánxiào", "Động từ", "Làm trò cười", 0],
["看法", "kànfǎ", "Danh từ", "Cách làm; Cách nhìn", 0],
["考虑", "kǎolǜ", "Động từ", "Suy nghĩ", 0],
["棵", "kē", "Lượng từ", "Cây; Ngọn", 0],
["可怜", "kělián", "Động từ", "Đáng thương", 0],
["肯定", "kěndìng", "Động từ", "Khẳng định; Tính từ; Trạng từ", 0],
["可是", "kěshì", "Liên từ", "Nhưng; Từ nối", 0],
["咳嗽", "késòu", "Động từ", "Ho", 0],
["可惜", "kěxi", "Động từ", "Đáng tiếc; Tính từ", 0],
["科学", "kēxué", "Danh từ", "Khoa học", 0],
["恐怕", "kǒngpà", "Động từ", "E rằng; Sợ rằng", 0],
["空气", "kōngqì", "Danh từ", "Không khí", 0],
["苦", "kǔ", "Tính từ", "Khổ", 0],
["宽", "kuān", "Tính từ", "Rộng", 0],
["困", "kùn", "Tính từ", "Khốn khổ; Buồn ngủ", 0],
["困难", "kùnnán", "Tính từ", "Khó khăn; Danh từ", 0],
["扩大", "kuòdà", "Động từ", "Mở rộng", 0],
["辣", "là", "Danh từ", "Cay", 0],
["拉", "lā", "Động từ", "Kéo", 0],
["来不及/来得及", "láibují / láidéjí", "Động từ", "Không đến kịp / Đến kịp", 0],
["来不及/", "láibují láidéjí", "Động từ", "Không đến kịp/", 0],
["垃圾桶", "lājī tǒng", "Danh từ", "Thùng rác", 0],
["懒", "lǎn", "Tính từ", "Lười", 0],
["浪费", "làngfèi", "Động từ", "Lãng phí", 0],
["浪漫", "làngmàn", "Tính từ", "Lãng mạn", 0],
["老虎", "lǎohǔ", "Danh từ", "Con hổ", 0],
["冷静", "lěngjìng", "Tính từ", "Bình tĩnh; Yên tĩnh; Tĩnh lại", 0],
["俩", "liǎ", "Số từ", "Hai; Số 2; Chỉ 2 người", 0],
["连", "lián", "Danh từ", "Liên; Liên tiếp", 0],
["亮", "liàng", "Tính từ", "Sáng, sáng lên, phát sáng; Bóng", 0],
["凉快", "liángkuai", "Tính từ", "Lạnh lẽo; Mát mẻ", 0],
["联系", "liánxì", "Động từ", "Liên hệ", 0],
["聊天", "liáotiān", "Động từ", "Nói chuyện", 0],
["理发", "lǐfà", "Động từ", "Cắt tóc", 0],
["厉害", "lìhai", "Tính từ", "Lợi hại; Giỏi", 0],
["理解", "lǐjiě", "Động từ", "Lý giải; Hiểu", 0],
["礼貌", "lǐmào", "Danh từ", "Lễ phép; Tính từ; Lễ độ; Lịch sự", 0],
["另外", "lìngwài", "Phó từ", "Ngoài ra; Liên từ", 0],
["力气", "lìqì", "Danh từ", "Sức lực; Hơi sức", 0],
["例如", "lìrú", "Danh từ", "Ví dụ", 0],
["留", "liú", "Động từ", "Ở lại Lưu lại", 0],
["流泪", "liúlèi", "Động từ", "Rơi lệ; Khóc", 0],
["流利", "liúlì", "Động từ", "Lưu loát", 0],
["流行", "liúxíng", "Danh từ", "Thịnh hành", 0],
["留学", "liúxué", "Động từ", "Du học", 0],
["理想", "lǐxiǎng", "Danh từ", "Lí tưởng; Tính từ", 0],
["乱", "luàn", "Động từ", "Loạn", 0],
["律师", "lǜshī", "Danh từ", "Luật sư", 0],
["麻烦", "máfan", "Động từ", "Làm phiền", 0],
["马虎", "mǎhǔ", "Tính từ", "Qua loa; Sơ sài", 0],
["满", "mǎn", "Tính từ", "Đầy Mãn", 0],
["毛巾", "máojīn", "Danh từ", "Khăn", 0],
["美丽", "měilì", "Tính từ", "Đẹp đẽ; Mĩ lệ", 0],
["梦", "mèng", "Danh từ", "Giấc mơ; Giấc mộng", 0],
["免费", "miǎnfèi", "Tính từ", "Miễn phí; Trạng từ", 0],
["密码", "mìmǎ", "Danh từ", "Mật mã", 0],
["民族", "mínzú", "Danh từ", "Dân tộc", 0],
["目的", "mùdì", "Danh từ", "Mục đích", 0],
["母亲", "mǔqīn", "Danh từ", "Mẹ đẻ; Mẹ", 0],
["耐心", "nàixīn", "Tính từ", "Kiên nhẫn", 0],
["难道", "nándào", "Trạng từ", "Lẽ nào", 0],
["难受", "nánshòu", "Tính từ", "Khó chịu", 0],
["内", "nèi", "Danh từ Phương vị từ", "Bên trong", 0],
["内容", "nèiróng", "Danh từ", "Nội dung", 0],
["能力", "nénglì", "Danh từ", "Năng lực", 0],
["年龄", "niánlíng", "Danh từ", "Tuổi", 0],
["弄", "nòng", "Động từ", "Làm", 0],
["农村", "nóngcūn", "Danh từ", "Nông thôn", 0],
["暖和", "nuǎnhuo", "Tính từ", "Ấm áp", 0],
["偶尔", "ǒu'ěr", "Trạng từ", "Thỉnh thoảng", 0],
["排列", "páiliè", "Động từ", "Xếp hàng Sắp xếp; xếp đặt", 0],
["判断", "pànduàn", "Động từ", "Phán đoán", 0],
["陪", "péi", "Động từ", "Cùng; theo; đưa; Bên cạnh", 0],
["骗", "piàn", "Động từ", "Lừa", 0],
["篇", "piān", "Lượng từ", "Đoạn", 0],
["皮肤", "pífū", "Danh từ", "Làn da; Da", 0],
["乒乓球", "pīngpāng qiú", "Danh từ", "Bóng bàn", 0],
["平时", "píngshí", "Danh từ chỉ thời gian Trạng từ", "Bình thường", 0],
["瓶子", "píngzi", "Danh từ", "Bình; Lọ", 0],
["批评", "pīpíng", "Động từ", "Phê bình; Nhắc nhở", 0],
["脾气", "píqi", "Danh từ", "Tính khí", 0],
["破", "pò", "Động từ", "Vỡ Phá; Tính từ", 0],
["普遍", "pǔbiàn", "Danh từ", "Phổ biến", 0],
["墙", "qiáng", "Danh từ", "Tường", 0],
["千万", "qiānwàn", "Danh từ", "Ngàn vạn", 0],
["签证", "qiānzhèng", "Danh từ", "Thị thực; visa", 0],
["桥", "qiáo", "Danh từ", "Cây cầu", 0],
["敲", "qiāo", "Động từ", "Gõ, đập", 0],
["巧克力", "qiǎokèlì", "Danh từ", "Socola", 0],
["其次", "qícì", "Liên từ", "Lần khác; Thứ hai", 0],
["起飞", "qǐfēi", "Động từ", "Cất cánh", 0],
["气候", "qìhòu", "Danh từ", "Khí hậu", 0],
["起来", "qǐlái", "Động từ", "Đứng lên", 0],
["轻", "qīng", "Tính từ", "Nhẹ", 0],
["请假", "qǐngjià", "Động từ", "Xin nghỉ", 0],
["请客", "qǐngkè", "Động từ", "Mời khách", 0],
["情况", "qíngkuàng", "Danh từ", "Tình trạng; Tình hình", 0],
["轻松", "qīngsōng", "Tính từ", "Nhẹ nhõm Nhẹ nhàng", 0],
["亲戚", "qīnqī", "Danh từ", "Thân thích; Họ hàng", 0],
["穷", "qióng", "Tính từ", "Nghèo", 0],
["其中", "qízhōng", "Động từ", "Trong đó", 0],
["取", "qǔ", "Động từ", "lấy", 0],
["全部", "quánbù", "Danh từ", "Toàn bộ", 0],
["区别", "qūbié", "Danh từ", "Khác biệt", 0],
["却", "què", "Động từ", "Lùi, làm mất đi Lại,; Phó từ mà lại, nhưng mà", 0],
["缺点", "quēdiǎn", "Danh từ", "Khuyết điểm", 0],
["缺少", "quēshǎo", "Động từ", "Thiếu hụt", 0],
["确实", "quèshí", "Tính từ", "Đích xác", 0],
["群", "qún", "Danh từ", "Bầy; Lượng từ; Đàn", 0],
["然而", "rán'ér", "Phó từ", "Nhưng mà, thế mà", 0],
["热闹", "rènào", "Tính từ", "Náo nhiệt; Sôi động", 0],
["仍", "réng", "Phó từ", "Dựa vào; Dựa theo vẫn", 0],
["仍然", "réngrán", "Phó từ", "Vẫn; Vẫn cứ; Tiếp tục", 0],
["任何", "rènhé", "Đại từ", "Bất kì", 0],
["人民币", "rénmínbì", "Danh từ", "Nhân dân tệ", 0],
["任务", "rènwù", "Danh từ", "Nhiệm vụ", 0],
["日记", "rìjì", "Danh từ", "Nhật ký", 0],
["软", "ruǎn", "Tính từ", "Mềm", 0],
["入口", "rùkǒu", "Động từ", "Nhập khẩu", 0],
["散步", "sàn bù", "Động từ", "Đi bộ", 0],
["沙发", "shāfā", "Danh từ", "Sô pha", 0],
["商量", "shāngliàng", "Động từ", "Thương lượng; Bàn bạc", 0],
["伤心", "shāngxīn", "Tính từ", "Thương tâm", 0],
["稍微", "shāowéi", "phó từ", "Ít, hơi hơi", 0],
["社会", "shèhuì", "Danh từ", "Xã hội", 0],
["深", "shēn", "Tính từ", "Sâu", 0],
["剩", "shèng", "Động từ", "Thừa; Còn lại", 0],
["省", "shěng", "Danh từ", "Tỉnh Tiết kiệm", 0],
["生活", "shēnghuó", "Danh từ", "Cuộc sống", 0],
["生命", "shēngmìng", "Danh từ", "Sinh mệnh; Tính mệnh", 0],
["申请", "shēnqǐng", "Động từ", "Nộp đơn; Đâm đơn; Đưa đơn", 0],
["甚至", "shènzhì", "Liên từ", "Thậm chí; Trạng từ", 0],
["试", "shì", "Động từ", "Thử", 0],
["失败", "shībài", "Động từ", "Thất bại", 0],
["市场", "shìchǎng", "Danh từ", "Chợ; Thị trường", 0],
["十分", "shífēn", "Phó từ", "Mười phần; Thật; Cực kì", 0],
["师傅", "shīfù", "Danh từ", "Sư phụ; Thầy", 0],
["适合", "shìhé", "Động từ", "Thích hợp", 0],
["实际", "shíjì", "Danh từ", "Thực tế tính từ", 0],
["食品", "shípǐn", "Danh từ", "Thực phẩm", 0],
["湿润", "shīrùn", "Danh từ", "Ẩm ướt", 0],
["失望", "shīwàng", "Tính từ", "Thất vọng", 0],
["适应", "shìyìng", "Động từ", "Thích ứng", 0],
["使用", "shǐyòng", "Động từ", "Sử dụng", 0],
["实在", "shízài", "Tính từ", "Đích thực xác thực; Trạng từ; Kì thực", 0],
["狮子", "shīzi", "Danh từ", "Sư tử", 0],
["收", "shōu", "Động từ", "Nhận", 0],
["受不了", "shòu bùliǎo", "Động từ", "Chịu không nổi", 0],
["收到", "shōu dào", "Động từ", "Nhận được", 0],
["首都", "shǒudū", "Danh từ", "Thủ đô", 0],
["售货员", "shòuhuòyuán", "Danh từ", "Nhân viên bán hàng", 0],
["收入", "shōurù", "Động từ", "Thu nhập", 0],
["收拾", "shōushi", "Động từ", "Thu dọn; Chỉnh lý", 0],
["首先", "shǒuxiān", "Từ nối", "Đầu tiên; Trạng từ", 0],
["输", "shū", "Động từ", "Thua", 0],
["帅", "shuài", "Tính từ", "Đẹp; Đẹp trai; Soái", 0],
["数量", "shùliàng", "Danh từ", "Số lượng", 0],
["顺便", "shùnbiàn", "Trạng từ", "Thuận tiện; nhân tiện; tiện thể", 0],
["顺利", "shùnlì", "Tính từ", "Thuận lợi", 0],
["顺序", "shùnxù", "Danh từ", "Thứ tự", 0],
["说明", "shuōmíng", "Động từ", "Nói rõ; Danh từ; Thuyết minh", 0],
["硕士", "shuòshì", "Danh từ", "Thạc sĩ", 0],
["熟悉", "shúxī", "Động từ", "Hiểu rõ", 0],
["数字", "shùzì", "Danh từ", "Chữ số", 0],
["死", "sǐ", "Động từ", "Chết; Danh từ; Mất; Ra đi; Qua đời", 0],
["算", "suàn", "Động từ", "Tính toán; Trạng từ; Coi là; Đoán", 0],
["酸", "suān", "Danh từ", "Chua", 0],
["速度", "sùdù", "Danh từ", "Tốc độ", 0],
["随便", "suíbiàn", "Động từ", "Tùy ý; Tính từ; Tùy tiện", 0],
["随着", "suízhe", "Từ nối", "Theo ….; Cùng với...", 0],
["塑料袋", "sùliào dài", "Danh từ", "Túi nilon", 0],
["孙子", "sūnzi", "Danh từ", "Cháu", 0],
["所有", "suǒyǒu", "Danh từ", "Tất cả; Lượng từ; Toàn bộ", 0],
["台", "tái", "Danh từ", "Đài/bệ Sân thượng", 0],
["抬", "tái", "Động từ", "Nhấc; Khiêng; Giơ lên", 0],
["态度", "tàidù", "Danh từ", "Thái độ", 0],
["谈", "tán", "Động từ", "Nói chuyện", 0],
["趟", "tàng", "Lượng từ", "Chuyến", 0],
["糖", "táng", "Danh từ", "Đường", 0],
["汤", "tāng", "Danh từ", "Canh Soup/súp", 0],
["躺", "tǎng", "Động từ", "Nằm", 0],
["弹钢琴", "tángāngqín", "Động từ", "Đánh đàn", 0],
["讨厌", "tǎoyàn", "Động từ", "Ghét bỏ", 0],
["特点", "tèdiǎn", "Danh từ", "Đặc điểm", 0],
["填空", "tiánkòng", "Động từ", "Điền vào chỗ trống", 0],
["条件", "tiáojiàn", "Danh từ", "Điều kiện", 0],
["提供", "tígōng", "Động từ", "Cung cấp", 0],
["挺", "tǐng", "Phó từ", "Rất", 0],
["停止", "tíngzhǐ", "Động từ", "Dừng lại; Đình chỉ", 0],
["提前", "tíqián", "Động từ", "Đề cập tới trước", 0],
["提醒", "tíxǐng", "Động từ", "Nhắc nhở", 0],
["通过", "tōngguò", "Động từ", "Thông qua; Đi qua; Vượt qua", 0],
["同情", "tóngqíng", "Động từ", "Đồng tình; Đồng cảm", 0],
["通知", "tōngzhī", "Động từ", "Thông báo", 0],
["腿", "tuǐ", "Danh từ", "chân; cẳng; giò", 0],
["推迟", "tuīchí", "Động từ", "Hoãn lại; Lùi lại; Chậm lại", 0],
["脱", "tuō", "Động từ", "Cởi", 0],
["往", "wǎng", "Động từ", "Đi Tới", 0],
["网球", "wǎngqiú", "Danh từ", "Quần vợt; Tennis", 0],
["往往", "wǎngwǎng", "Phó nối", "Thường hay; Nơi nơi; khắp nơi", 0],
["网站", "wǎngzhàn", "Danh từ", "Website Trang web", 0],
["完全", "wánquán", "Tính từ", "Hoàn toàn", 0],
["袜子", "wàzi", "Danh từ", "Tất", 0],
["味道", "wèidào", "Danh từ", "Hương vị", 0],
["危险", "wēixiǎn", "Tính từ", "Nguy hiểm; Danh từ", 0],
["温度", "wēndù", "Danh từ", "Nhiệt độ", 0],
["文章", "wénzhāng", "Danh từ", "Đoạn văn", 0],
["握手", "wòshǒu", "Động từ", "Bắt tay", 0],
["无", "wú", "Danh từ/động từ", "Không; Vô", 0],
["误会", "wùhuì", "động từ", "Hiểu nhầm/lầm", 0],
["无聊", "wúliáo", "Tính từ", "Buồn chán; Nhạt nhẽo", 0],
["无论", "wúlùn", "Từ nối", "Bất luận", 0],
["污染", "wūrǎn", "Động từ", "Ô nhiễm", 0],
["咸", "xián", "Tính từ", "Mặn", 0],
["现代", "xiàndài", "Danh từ", "Hiện đại", 0],
["香", "xiāng", "Danh từ/tính từ", "Thơm", 0],
["响", "xiǎng", "Động từ/tính từ", "Vang lên; kêu lên; Vang", 0],
["相反", "xiāngfǎn", "Danh từ", "Tương phản; Ngược lại", 0],
["详细", "xiángxì", "Tính từ", "Kĩ càng; Tỉ mỉ", 0],
["羡慕", "xiànmù", "Động từ", "Ngưỡng mộ", 0],
["限制", "xiànzhì", "Động từ", "Giới hạn", 0],
["效果", "xiàoguǒ", "Danh từ", "Hiệu quả", 0],
["笑话", "xiàohuà", "Danh từ", "Truyện cười", 0],
["小说", "xiǎoshuō", "Danh từ", "Tiểu thuyết", 0],
["消息", "xiāoxi", "Danh từ", "Tin tức", 0],
["西红柿", "xīhóngshì", "Danh từ", "Cà chua", 0],
["行", "xíng", "Danh từ/Động từ/tính từ", "Được, ok; Đi; Làm; Hành", 0],
["醒", "xǐng", "Động từ", "Tỉnh", 0],
["性别", "xìngbié", "Danh từ", "Giới tính", 0],
["兴奋", "xīngfèn", "Tính từ", "Hưng phấn", 0],
["幸福", "xìngfú", "Tính từ", "Hạnh phúc", 0],
["性格", "xìnggé", "Danh từ", "Tính cách", 0],
["辛苦", "xīnkǔ", "Tính từ", "Khổ cực", 0],
["心情", "xīnqíng", "Danh từ", "Tâm tình; Tâm trạng", 0],
["信任", "xìnrèn", "động từ", "Tín nhiệm; Tin tưởng", 0],
["信心", "xìnxīn", "Danh từ", "Niềm tin", 0],
["信用卡", "xìnyòngkǎ", "Danh từ", "Thẻ tín dụng", 0],
["修", "xiū", "Động từ", "Sửa", 0],
["洗衣机", "xǐyījī", "Danh từ", "Máy giặt", 0],
["吸引", "xīyǐn", "Động từ", "Hấp dẫn", 0],
["许多", "xǔduō", "Số từ/Phó từ", "Rất nhiều", 0],
["雪", "xuě", "Danh từ", "Tuyết", 0],
["呀", "yā", "Từ cảm thán", "Ya; A; Ô nhé", 0],
["牙膏", "yágāo", "Danh từ", "Kem đánh răng", 0],
["压力", "yālì", "danh từ", "Áp lực", 0],
["盐", "yán", "Danh từ", "Muối", 0],
["演出", "yǎnchū", "Động từ", "Diễn xuất; Biểu diễn", 0],
["养成", "yǎngchéng", "Động từ", "Nuôi dưỡng thành…; Dưỡng dục thành …", 0],
["严格", "yángé", "Tính từ", "Nghiêm khắc", 0],
["阳光", "yángguāng", "Danh từ", "Ánh nắng mặt trời", 0],
["样子", "yàngzi", "Danh từ", "Kiểu dáng, hình dáng; Mẫu , vẻ", 0],
["研究生", "yánjiūshēng", "Danh từ", "Nghiên cứu sinh", 0],
["演员", "yǎnyuán", "Danh từ", "Diễn viên", 0],
["严重", "yánzhòng", "Tính từ", "Nghiêm trọng", 0],
["邀请", "yāoqǐng", "Động từ", "Mời", 0],
["钥匙", "yàoshi", "Danh từ", "Chìa khóa", 0],
["亚洲", "yàzhōu", "Danh từ", "Châu Á", 0],
["页", "yè", "Danh từ", "Trang; Tờ", 0],
["也许", "yěxǔ", "phó từ", "Có lẽ E rằng", 0],
["叶子", "yèzi", "Danh từ", "Chiếc lá", 0],
["亿", "yì", "Số từ", "Trăm triệu", 0],
["以", "yǐ", "Từ nối", "Lấy; Bởi vì; Để; Nhằm", 0],
["意见", "yìjiàn", "Danh từ", "Ý kiến", 0],
["因此", "yīncǐ", "Từ nối", "Do đó Vì vậy", 0],
["硬", "yìng", "Tính từ", "Cứng", 0],
["赢", "yíng", "động từ", "Thắng", 0],
["饮料", "yǐnliào", "Danh từ", "Thức uống", 0],
["引起", "yǐnqǐ", "Động từ", "Gây nên; Dẫn tới", 0],
["印象", "yìnxiàng", "Danh từ", "Ấn tượng", 0],
["一切", "yíqiè", "Từ nối", "Tất cả Tất; Liên từ thảy", 0],
["艺术", "yìshù", "Danh từ", "Nghệ thuật", 0],
["勇敢", "yǒnggǎn", "tính từ", "Dũng cảm", 0],
["永远", "yǒngyuǎn", "Tính từ/phó từ", "Mãi mãi Vĩnh viễn", 0],
["由", "yóu", "Từ nối", "Vì; Do", 0],
["优点", "yōudiǎn", "Danh từ", "Ưu điểm; Điểm tốt", 0],
["友好", "yǒuhǎo", "Danh từ", "Bạn thân/ tốt; Hữu hảo", 0],
["幽默", "yōumò", "Tính từ", "Hài hước; Vui tính", 0],
["尤其", "yóuqí", "Liên từ", "Đặc biệt; Từ nối", 0],
["有趣", "yǒuqù", "Tính từ", "Thú vị", 0],
["优秀", "yōuxiù", "Tính từ", "Xuất sắc", 0],
["友谊", "yǒuyì", "Danh từ", "Hữu nghị", 0],
["由于", "yóuyú", "Liên từ", "Bởi vì; Từ nối", 0],
["与", "yǔ", "Liên từ", "Với; Và", 0],
["圆", "yuán", "Tính từ", "Tròn; Toàn vẹn", 0],
["原来", "yuánlái", "Trạng từ", "Hóa ra; Vốn dĩ; Lúc đầu", 0],
["原谅", "yuánliàng", "Động từ", "Tha thứ; Thứ lỗi", 0],
["原因", "yuányīn", "Danh từ", "Nguyên nhân", 0],
["阅读", "yuèdú", "Động từ", "Đọc", 0],
["约会", "yuēhuì", "Động từ", "Hẹn hò; Tụ họp; Họp ...", 0],
["语法", "yǔfǎ", "Danh từ", "Ngữ pháp", 0],
["愉快", "yúkuài", "Tính từ", "Vui vẻ", 0],
["羽毛球", "yǔmáoqiú", "Danh từ", "Cầu lông", 0],
["允许", "yǔnxǔ", "Động từ", "Cho phép; Đồng ý cho làm ...", 0],
["于是", "yúshì", "Liên từ", "Thế là; Từ nối", 0],
["预习", "yùxí", "Động từ", "Chuẩn bị bài", 0],
["语言", "yǔyán", "Danh từ", "Ngôn ngữ", 0],
["脏", "zàng", "Tính từ", "Bẩn", 0],
["咱们", "zánmen", "Đại từ", "Chúng ta", 0],
["暂时", "zànshí", "Trạng từ", "Tạm thời", 0],
["杂志", "zázhì", "Danh từ", "Tạp chí", 0],
["增加", "zēngjiā", "Động từ", "Tăng thêm/ lên", 0],
["增长", "zēngzhǎng", "Động từ", "Tăng trưởng", 0],
["责任", "zérèn", "Danh từ", "Trách nhiệm", 0],
["窄", "zhǎi", "Tính từ", "Chật, hẹp", 0],
["招聘", "zhāopìn", "Danh từ", "Tuyển dụng; Động từ", 0],
["正常", "zhèngcháng", "Tính từ", "Bình thường", 0],
["正好", "zhènghǎo", "Trạng từ", "Vừa vặn; Vừa hay; Vừa đúng lúc", 0],
["整理", "zhěnglǐ", "Động từ", "Chỉnh lý, sắp xếp; Thu dọn", 0],
["证明", "zhèngmíng", "Động từ", "Chứng minh", 0],
["整齐", "zhěngqí", "Tính từ", "Gọn gàng; Ngăn nắp", 0],
["正确", "zhèngquè", "Tính từ", "Chính xác", 0],
["正式", "zhèngshì", "tính từ", "Chính thức", 0],
["真正", "zhēnzhèng", "Trạng từ", "Chân chính; Chính xác; Thực sự", 0],
["之", "zhī", "Danh từ/đại từ/trợ từ", "Tới, hướng về; Cái đó, người đó; Của", 0],
["只", "zhǐ", "phó từ", "Chỉ, chỉ có", 0],
["指", "zhǐ", "Động từ", "Chỉ", 0],
["支持", "zhīchí", "Động từ", "Ủng hộ", 0],
["值得", "zhídé", "Động từ", "Đáng", 0],
["只好", "zhǐhǎo", "phó từ", "Đành phải", 0],
["直接", "zhíjiē", "tính từ/trạng từ", "Trực tiếp", 0],
["质量", "zhìliàng", "Danh từ", "Chất lượng", 0],
["至少", "zhìshǎo", "Trạng từ", "Ít nhất; Tối thiểu", 0],
["知识", "zhīshi", "Danh từ", "Kiến thức; Tri thức", 0],
["植物", "zhíwù", "Danh từ", "Thực vật, cây cối", 0],
["只要", "zhǐyào", "Động từ", "Chỉ cần", 0],
["职业", "zhíyè", "Danh từ", "Nghề nghiệp", 0],
["制造", "zhìzào", "Động từ", "Chế tạo; Sản xuất", 0],
["重点", "zhòngdiǎn", "danh từ Trạng từ", "Trọng điểm", 0],
["重视", "zhòngshì", "Động từ", "Coi trọng; chú trọng", 0],
["中文", "zhōngwén", "Danh từ", "Tiếng Trung", 0],
["周围", "zhōuwéi", "danh từ", "Xung quanh; Chu vi", 0],
["猪", "zhū", "Danh từ", "Con lợn", 0],
["赚", "zhuàn", "Động từ", "Kiếm Lợi nhuận", 0],
["撞", "zhuàng", "Động từ", "Đụng; Chạm", 0],
["专门", "zhuānmén", "Danh từ", "Chuyên môn", 0],
["专业", "zhuānyè", "Danh từ", "Chuyên ngành", 0],
["主动", "zhǔdòng", "tính từ", "Chủ động", 0],
["祝贺", "zhùhè", "Động từ", "Chúc mừng", 0],
["逐渐", "zhújiàn", "trạng từ", "Dần dần", 0],
["著名", "zhùmíng", "Tính từ", "Nổi tiếng", 0],
["准确", "zhǔnquè", "Tính từ", "Chính xác; Đích xác; Đúng đắn", 0],
["准时", "zhǔnshí", "Tính từ", "Chuẩn giờ; Đúng giờ", 0],
["自然", "zìrán", "Danh từ", "Tự nhiên", 0],
["仔细", "zǐxì", "Tính từ", "Tỉ mỉ Cẩn thận", 0],
["总结", "zǒngjié", "Động từ", "Tổng kết", 0],
["租", "zū", "Động từ", "Thuê mướn", 0],
["组成", "zǔchéng", "Động từ", "Cấu thành; Tạo thành", 0],
["嘴", "zuǐ", "Danh từ", "Miệng mồm", 0],
["最好", "zuì hǎo", "Trạng từ", "Tốt nhất", 0],
["最后", "zuìhòu", "Danh từ", "Cuối cùng", 0],
["尊重", "zūnzhòng", "Động từ", "Tôn trọng", 0],
["座", "zuò", "Danh từ / Lượng từ", "Chỗ ngồi; Tòa, ngôi, hòn", 0],
["做生意", "zuò shēngyì", "Động từ", "Làm ăn Làm kinh doanh", 0],
["座位", "zuòwèi", "Danh từ", "Chỗ ngồi", 0],
["作者", "zuòzhě", "Danh từ", "Tác giả", 0],
["组织", "zǔzhī", "Danh từ/Động từ", "Tổ chức", 0]);
